# -*- coding: utf-8 -*-
"""v0.23.23 bump：version.json(version/note/noteEn) + sw.js CACHE + index.html APP_VERSION + download.html 兜底 ×2。
幂等。apk 块（versionCode/url/md5/size）不动——由 apk.yml 在出包时回写真实值，避免先发占位值。
本次为「界面视觉与智能化升级」P0 止血版：修攻略页白底黑字默认按钮 + 对话卡裸文本。
"""
import os, json, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
VJ = os.path.join(ROOT, 'version.json')
SW = os.path.join(ROOT, 'sw.js')
IH = os.path.join(ROOT, 'index.html')
DH = os.path.join(ROOT, 'download.html')
NEW = '0.23.23'
PREV = '0.23.22'

# ---- version.json（仅顶层 version/note/noteEn；apk 块留给 CI） ----
vj = json.load(open(VJ, encoding='utf-8'))
if vj.get('version') == NEW:
    print('version.json version already %s' % NEW)
else:
    vj['version'] = NEW
    vj['updated'] = '2026-09-23'
    vj['note'] = ('v0.23.23：界面视觉修复（P0 止血）。'
      '（1）修复「攻略中心」9 个分区渲染成白底黑字默认按钮的问题——cgZoneHtml 生成的 '
      '.cg-zone/.cg-zhead/.zi/.zt/.zc/.chev/.cg-zbody/.cg-dialog 共 8 个样式类此前从未定义过，'
      '整块落到浏览器默认样式，与暗色主题完全脱节；现已按卡片规范补齐，分区标题与 0/4 计数用网格分栏正确分开。'
      '（2）修复「攻略中心」情景对话卡显示为纯文本堆叠的问题——对话卡样式原先只写在对话卡页作用域下，'
      '攻略页复用同一套标记却完全不生效；现已在攻略页补上同源样式，说话人分色、YOU 行红框、拼音层级全部恢复。'
      '（3）新增设计令牌 --txt-3/--line-strong/--red-text/--ok/--warn，收编此前散落多种灰色兜底值的两枚孤儿变量。'
      '（4）修复品牌红在深色底上对比度仅 4.19:1（低于无障碍 AA 标准 4.5）的可读性问题：'
      '小号红字统一改用 --red-text（对比度 6.33:1）。网页与 APK 同版本上线。')
    en = ('v0.23.23: UI visual fixes (P0 triage). '
      '(1) Fixed the City Guide where all 9 zones rendered as default white buttons: the 8 style classes '
      '(.cg-zone/.cg-zhead/.zi/.zt/.zc/.chev/.cg-zbody/.cg-dialog) generated by cgZoneHtml had never been defined, '
      'so the whole block fell back to browser defaults and clashed with the dark theme; they are now styled to the '
      'card spec, and the zone title and the 0/4 counter are properly separated by a grid layout. '
      '(2) Fixed the City Guide dialogue card rendering as a raw text dump: the dialogue styles were scoped to the '
      'dialogue-card page only, so reusing the same markup inside the guide page had no effect; the guide page now '
      'carries equivalent styling, restoring speaker colour-coding, the red YOU row, and the pinyin hierarchy. '
      '(3) Added design tokens --txt-3/--line-strong/--red-text/--ok/--warn, folding in two orphan variables that had '
      'been falling back to several inconsistent greys. (4) Fixed a readability issue where the brand red only '
      'reached 4.19:1 contrast on dark backgrounds (below the 4.5 AA threshold): small red text now uses --red-text '
      '(6.33:1). Web and APK ship together at this version.')
    vj['noteEn'] = [en] + (vj.get('noteEn') or [])
    json.dump(vj, open(VJ, 'w', encoding='utf-8'), ensure_ascii=False, indent=2)
    open(VJ, 'a', encoding='utf-8').write('\n')
    print('version.json -> %s' % NEW)

# ---- sw.js CACHE ----
s = open(SW, encoding='utf-8').read()
if "var CACHE = 'sinoky-v%s'" % NEW in s:
    print('sw.js already %s' % NEW)
else:
    old = "var CACHE = 'sinoky-v%s'" % PREV
    c = s.count(old)
    if c != 1:
        print('ABORT sw.js CACHE anchor %s count=%d' % (PREV, c)); sys.exit(1)
    s = s.replace(old, "var CACHE = 'sinoky-v%s'" % NEW, 1)
    open(SW, 'w', encoding='utf-8').write(s)
    print('sw.js CACHE -> sinoky-v%s' % NEW)

# ---- index.html APP_VERSION ----
h = open(IH, encoding='utf-8').read()
if "var APP_VERSION = '%s'" % NEW in h:
    print('index.html APP_VERSION already %s' % NEW)
else:
    old = "var APP_VERSION = '%s'" % PREV
    c = h.count(old)
    if c != 1:
        print('ABORT index.html APP_VERSION anchor %s count=%d' % (PREV, c)); sys.exit(1)
    h = h.replace(old, "var APP_VERSION = '%s'" % NEW, 1)
    open(IH, 'w', encoding='utf-8').write(h)
    print('index.html APP_VERSION -> %s' % NEW)

# ---- download.html 兜底 APK url ×2 ----
d = open(DH, encoding='utf-8').read()
if 'Sinoky-v%s-release.apk' % NEW in d:
    print('download.html already %s' % NEW)
else:
    old = 'Sinoky-v%s-release.apk' % PREV
    c = d.count(old)
    if c == 0:
        print('ABORT download.html anchor %s not found (count=%d)' % (PREV, c)); sys.exit(1)
    d = d.replace(old, 'Sinoky-v%s-release.apk' % NEW)
    open(DH, 'w', encoding='utf-8').write(d)
    print('download.html fallback -> Sinoky-v%s-release.apk (%d hits)' % (NEW, c))
print('DONE')
